apiVersion: v1
kind: Pod
metadata:
  name: ebpf-profiler
spec:
  hostPID: true
  containers:
  - name: ebpf-profiler
    image: {{BPF_TOOLS_IMAGE}}
    imagePullPolicy: Always
    securityContext:
      privileged: true
    command:
    - "/bin/bash"
    - "-c"
    - |-
      BPF_TOOLS_CONTAINERID=$(docker ps | grep k8s_${BPF_TOOLS_CONTAINER}_${BPF_TOOLS_POD} | awk '{print $1}')
      BPF_TOOLS_PID=$(docker inspect $BPF_TOOLS_CONTAINERID --format '{{ .State.Pid }}')
      echo "profiling pid $BPF_TOOLS_PID for seconds $BPF_TOOLS_SECONDS"
      BPF_TOOLS_SECONDS=$(echo $BPF_TOOLS_SECONDS | sed s/\"//g)
      ./bcc/tools/profile.py -dF 99 -f $BPF_TOOLS_SECONDS -p $BPF_TOOLS_PID | ./FlameGraph/flamegraph.pl > ${BPF_TOOLS_CONTAINER}.svg
      echo "profiling complete"
      sleep 30s #gives our script chance to copy out the flamegraph
    env:
    - name: BPF_TOOLS_SECONDS
      value: "{{BPF_TOOLS_SECONDS}}"
    - name: BPF_TOOLS_POD
      value: {{BPF_TOOLS_POD}}
    - name: BPF_TOOLS_CONTAINER
      value: {{BPF_TOOLS_CONTAINER}}
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker
      - mountPath: /sys/kernel/debug
        name: kernel-debug
      - mountPath: /sys/fs/cgroup
        name: fs-cgroup
      - mountPath: /sys/fs/bpf
        name: fs-bpf
  nodeSelector:
    kubernetes.io/hostname: {{BPF_TOOLS_NODE}} # you can bind to a specific agent
  imagePullSecrets:
  - name: registrykey
  volumes:
    - name: docker
      hostPath: 
        path: /var/run/docker.sock
    - name: kernel-debug
      hostPath:
        path: /sys/kernel/debug
    - name: fs-cgroup
      hostPath:
        path: /sys/fs/cgroup
    - name: fs-bpf
      hostPath:
        path: /sys/fs/bpf
